// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96ht9eqvBY9wqiaGYUuAiEeD1iQTBPOU',
    appId: '1:414428666976:web:7974f37ad8381d0b3b7705',
    messagingSenderId: '414428666976',
    projectId: 'disty-899ea',
    authDomain: 'disty-899ea.firebaseapp.com',
    storageBucket: 'disty-899ea.firebasestorage.app',
    measurementId: 'G-BHTDJWLF48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9lny4l31bSGD-nLUOLAxuqUeEZucL9OE',
    appId: '1:414428666976:android:b6d92c93a27289953b7705',
    messagingSenderId: '414428666976',
    projectId: 'disty-899ea',
    storageBucket: 'disty-899ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7BnbeA09DdpCAc10bUWpk6ZBDySO6MgE',
    appId: '1:414428666976:ios:2e209b4226c99e7b3b7705',
    messagingSenderId: '414428666976',
    projectId: 'disty-899ea',
    storageBucket: 'disty-899ea.firebasestorage.app',
    iosBundleId: 'com.example.distimall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7BnbeA09DdpCAc10bUWpk6ZBDySO6MgE',
    appId: '1:414428666976:ios:2e209b4226c99e7b3b7705',
    messagingSenderId: '414428666976',
    projectId: 'disty-899ea',
    storageBucket: 'disty-899ea.firebasestorage.app',
    iosBundleId: 'com.example.distimall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB96ht9eqvBY9wqiaGYUuAiEeD1iQTBPOU',
    appId: '1:414428666976:web:9eeae9412f5242bb3b7705',
    messagingSenderId: '414428666976',
    projectId: 'disty-899ea',
    authDomain: 'disty-899ea.firebaseapp.com',
    storageBucket: 'disty-899ea.firebasestorage.app',
    measurementId: 'G-2MCVJLVVZ9',
  );
}
